# Generated by Django 4.1.4 on 2023-02-02 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devise', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_img',
            field=models.ImageField(upload_to=''),
        ),
    ]
